apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: nginx
spec:
  containers:
    - image: nginx:latest
      name: nginx 
      volumeMounts:
      - name: claim-volume
        mountPath: /var/log/nginx  
      ports:
      - containerPort: 80
  volumes:
    - name: claim-volume
      persistentVolumeClaim:
        claimName: my-pv-claim
